title = "default_config.toml"

#default_paths
theme_path = 'usr/share/themes/Mint-L-Dark/gtk-3.0/gtk-dark.css'
panel_path ='~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml'
whisker_menu_path = '~/.config/xfce4/panel/'

#testing_paths
# theme_path = 'resources/gtk-dark.css'
# panel_path = 'resources/xfce4-panel.xml'
# whisker_menu_path = 'resources/'

#colors (example values)
base_color = "#008899"
opacity = 0.70



