name: Rust Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on tags like v0.1.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Step 3: Install dependencies for cross-compiling (if needed)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      # Step 4: Build the project for Linux
      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      # Step 5: Create GitHub Release and upload the compiled binary
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/x86_64-unknown-linux-gnu/release/xfce4-pannel-and-menu-configurator
          tag: v0.1.0
          name: Release v0.1.0
          prerelease: false
